spring:
  application:
    name: price-service
  datasource:
    url: jdbc:h2:mem:pricedb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: false
  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
